version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: talentvision
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend/TalentVision_Back
      dockerfile: Dockerfile
    image: tondockerhubusername/talentvision-backend:latest
    environment:
      DATABASE_URL: postgres://postgres:secret@db:5432/talentvision
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend/TalentVision_front
      dockerfile: Dockerfile
    image: tondockerhubusername/talentvision-frontend:latest
    ports:
      - "3000:80"   # ou "3000:3000" si ton Dockerfile sert sur 3000
    depends_on:
      - backend

volumes:
  db_data:
