# Generated by Django 5.2.8 on 2025-11-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('model_type', models.CharField(choices=[('CV_ANALYZER', 'Analyseur de CV'), ('COMPATIBILITY_SCORER', 'Scoreur de compatibilité'), ('TURNOVER_PREDICTOR', 'Prédicteur de turnover')], max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
