# --------------------------
# Service PostgreSQL
# --------------------------
apiVersion: v1
kind: Service
metadata:
  name: talentvision-db
spec:
  selector:
    app: talentvision-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

# --------------------------
# Service Backend
# --------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: talentvision-backend-svc
spec:
  type: ClusterIP
  selector:
    app: talentvision-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

# --------------------------
# Service Frontend
# --------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: talentvision-frontend-svc
spec:
  type: NodePort
  selector:
    app: talentvision-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
