# Generated by Django 5.2.8 on 2025-11-08 23:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('TECHNICAL', 'Technique'), ('SOFT', 'Soft Skill'), ('LANGUAGE', 'Langue'), ('CERTIFICATION', 'Certification')], default='TECHNICAL', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='Exigences du poste')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publiée'), ('CLOSED', 'Fermée')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('required_skills', models.ManyToManyField(related_name='job_posts', to='recruitment.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('REVIEWED', 'Examinée'), ('SHORTLISTED', 'Pré-sélectionnée'), ('INTERVIEW', 'Entretien'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Refusée')], default='PENDING', max_length=20)),
                ('compatibility_score', models.FloatField(blank=True, help_text='Score de compatibilité (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('interview_notes', models.TextField(blank=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('WEBSITE', 'Site web'), ('LINKEDIN', 'LinkedIn'), ('REFERRAL', 'Recommandation'), ('OTHER', 'Autre')], default='WEBSITE', max_length=50)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobpost')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('candidate', 'job_post')},
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('CANDIDATE_MATCH', 'Candidat correspondant'), ('INTERNAL_MATCH', 'Matching interne'), ('HIGH_SCORE', 'Score élevé'), ('NEW_APPLICATION', 'Nouvelle candidature'), ('TURNOVER_RISK', 'Risque de départ')], max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('related_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='recruitment.application')),
                ('related_job_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='recruitment.jobpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalTalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.CharField(max_length=200)),
                ('experience_years', models.IntegerField(default=0)),
                ('performance_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('is_available_for_promotion', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internal_talent', to=settings.AUTH_USER_MODEL)),
                ('potential_positions', models.ManyToManyField(blank=True, related_name='potential_candidates', to='recruitment.jobpost')),
                ('skills', models.ManyToManyField(related_name='internal_talents', to='recruitment.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('cover_letter', models.TextField(blank=True)),
                ('cover_letter_file', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('experience_years', models.IntegerField(default=0)),
                ('current_position', models.CharField(blank=True, max_length=200)),
                ('education_level', models.CharField(blank=True, choices=[('BAC', 'Baccalauréat'), ('BAC+2', 'Bac+2'), ('BAC+3', 'Licence'), ('BAC+5', 'Master'), ('PHD', 'Doctorat')], max_length=50)),
                ('cv_analysis_status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En traitement'), ('COMPLETED', 'Terminé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('cv_analysis_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
                ('extracted_skills', models.ManyToManyField(blank=True, related_name='candidates', to='recruitment.skill')),
            ],
        ),
    ]
